[tools]
go = "1.26.0"

[tasks."go:vet"]
run = "go vet ./..."

[tasks."go:test"]
run = "go test -race $(go list ./... | grep -v /examples/)"

[tasks."go:upgrade"]
run = "go get -u ./... && go mod tidy"
